import Link from "next/link";
import { branding } from "@/config/branding";
import { BrandLockup, BrandMark, SparkIcon } from "./_components/ui";

/**
 * The marketing site — Brandeis the product, pitched to governments. Distinct
 * from the tenant portals it links to: /riverton is the living demo.
 *
 * Design: copy-forward, with rhythm carried by alternating grounds rather
 * than by imagery. All texture is CSS (see the MARKETING SITE block in
 * globals.css). The only binary assets are the owner's approved lockup —
 * two revisions, one per theme, in the footer. Raster, so each appears once
 * and large; see public/brand/README.md for why neither can be the chrome
 * logo.
 *
 * Every number and claim below is checkable in the codebase — no invented
 * customer counts, no testimonials. The product has no public users yet.
 */

const PILLARS = [
  {
    n: "01",
    t: "Deflect",
    h: "Answer before they file",
    d: "A plain-language answer box searches everything you have already released — keyword and semantic together — and hands residents the document in seconds. Many requests end as a download instead of a case file.",
  },
  {
    n: "02",
    t: "Fulfill",
    h: "Run every request on rails",
    d: "AI triage drafts scope and routing. Departments respond from a no-login link or by replying to the email. The statutory clock is computed from your state's law, and every extension records the basis it was granted on.",
  },
  {
    n: "03",
    t: "Defend",
    h: "An audit log for counsel",
    d: "Every action — human or AI — lands in an append-only event log with who, what, and why. Redactions are burned into regenerated bytes, never layered on top, and each release carries a named approver.",
  },
];

const STATS = [
  { n: "5", l: "state statute profiles", s: "California, Texas, Illinois, Washington, New York. Clock rules are data, not code." },
  { n: "0", l: "external services required", s: "AI, email, OCR and object storage are each opt-in behind an adapter." },
  { n: "1", l: "deployment, every agency", s: "Each with its own portal, seal, statute profile and isolated data." },
  { n: "100%", l: "of actions audit-logged", s: "Append-only, human and AI alike. No edit path, no delete path." },
];

const AGENTS = [
  {
    stage: "Before a request exists",
    name: "The answer box",
    does: "Searches everything your agency has already released — keyword and semantic, together — and answers residents in plain language with links to the documents. Many requests end here, as downloads instead of paperwork.",
    human: "Draws only on records already public. It cannot see anything else.",
  },
  {
    stage: "At intake",
    name: "Triage",
    does: "Reads the new request, drafts a scope summary, estimates complexity, suggests which departments should respond, and flags likely duplicates of requests you've already handled.",
    human: "A coordinator accepts, edits, or discards the scope before anything moves.",
  },
  {
    stage: "As records arrive",
    name: "Document review",
    does: "Reads each uploaded document, suggests a classification, and marks passages that may fall under a statutory exemption — with the citation it thinks applies.",
    human: "Suggestions land as cards on the document. Staff accept, edit, or dismiss each one.",
  },
  {
    stage: "In the redaction studio",
    name: "Redaction assist",
    does: "Runs a PII pass and proposes redactions span by span. Finalizing regenerates the document from clean bytes — accepted redactions are burned in, never layered on top.",
    human: "Every span is human-confirmed, and a leak check verifies the final artifact.",
  },
  {
    stage: "In correspondence",
    name: "Drafting",
    does: "Drafts clarification replies, extension notices, response letters, and denial letters with the appeal language your statute requires — grounded in the request's actual record.",
    human: "Letters go out under a staff name only after a staff member sends them.",
  },
  {
    stage: "Alongside your team",
    name: "The copilot & deadline watch",
    does: "A coordinator can ask the copilot about any request; drafted messages are editable in place and marked as AI-assisted. A nightly sweep watches every statutory clock and writes a digest of what's at risk.",
    human: "Every consultation is itself an audit event. The clock math is statute data, not model output.",
  },
];

export default function MarketingHome() {
  return (
    <div className="mk-page">
      {/* Product header — sticky glass, same .nav as the portals.
          Full lockup: approved mark + wordmark + tagline, all from branding.ts. */}
      <div className="nav mk-topnav">
        <div className="wrap nav-inner">
          <Link href="/" className="brand" aria-label={branding.productName}>
            <BrandLockup size={36} idPrefix="nav" />
          </Link>
          <nav className="nav-links" aria-label="Primary">
            <Link href="/riverton" className="nav-link">
              Live demo
            </Link>
            <Link href="/admin" className="nav-link">
              Platform console
            </Link>
            <Link href="/signup" className="btn btn-sm btn-maroon" style={{ marginLeft: 8 }}>
              Create your records office
            </Link>
          </nav>
        </div>
      </div>

      <main id="main">
        {/* Hero — the product wears the flag: deep navy, gold aurora, seal watermark */}
        <section className="mk-hero">
          <div className="wrap">
            <div className="mk-hero-grid">
            <div className="mk-hero-inner">
              <span className="mk-eyebrow">
                For city clerks, county counsel, and records officers
              </span>
              <h1 className="mk-display">
                Every response drafted for you.
                <br />
                <span className="mk-gold">Every decision still yours.</span>
              </h1>
              <hr className="letterhead-rule" aria-hidden />
              <p className="mk-lede">
                {branding.productName} triages each request, routes it to the right department,
                gathers the responsive records and drafts the response — then puts a named human in
                front of it before a word goes out. The statutory clock is computed from your
                state&apos;s law, not a spreadsheet.
              </p>
              <ul className="mk-proof">
                <li>Live demo, no signup</li>
                <li>5 state statute profiles</li>
                <li>Runs with zero external services</li>
                <li>Append-only audit log</li>
              </ul>
              <div style={{ display: "flex", gap: 12, marginTop: 32, flexWrap: "wrap" }}>
                <Link href="/signup" className="btn btn-gold" style={{ paddingInline: 24, paddingBlock: 12 }}>
                  Create your records office
                </Link>
                <Link href="/riverton" className="btn btn-outline-light" style={{ paddingInline: 24, paddingBlock: 12 }}>
                  Explore the live demo
                </Link>
              </div>
              <p className="mk-note">
                The demo is the real product, running for the fictional City of Riverton.
              </p>
            </div>

            {/* The thesis, made concrete. role=img with a description: the
                buttons are an illustration, not real controls, so assistive
                tech gets the summary instead of unfocusable fake widgets. */}
            <div>
              <div
                className="mk-panel"
                role="img"
                aria-label="Illustration: request PR-2026-00184 has been triaged, routed to Public Works and matched to 34 records automatically, and a response letter has been drafted for a staff member to send, edit or discard. The decision is written to the append-only audit log."
              >
                <div className="mk-panel-head">
                  <span className="mk-panel-id">PR-2026-00184</span>
                  <span className="mk-panel-sub">Public Works</span>
                  <span className="mk-panel-due">Due in 3 days</span>
                </div>
                <div className="mk-panel-steps">
                  <span className="mk-panel-step">Triaged</span>
                  <span className="mk-panel-step">Routed to Public Works</span>
                  <span className="mk-panel-step">34 records gathered</span>
                </div>
                <div className="mk-panel-body">
                  <p className="mk-panel-ask">
                    &ldquo;Emails between the Public Works director and Acme Paving about the Main
                    Street resurfacing contract, January through March.&rdquo;
                  </p>
                  <span className="mk-panel-kicker" style={{ marginTop: 16, display: "inline-flex" }}>
                    <SparkIcon />
                    Response drafted
                  </span>
                  <div className="mk-panel-letter">
                    Dear Ms. Alvarez — we identified 34 records responsive to your request. 31 are
                    released in full and attached. 3 are withheld under Gov. Code § 6254(c), with
                    the basis for each itemized below.
                    <em>Due 14 March · computed from Cal. Gov. Code § 7922.535</em>
                  </div>
                  <div className="mk-panel-acts">
                    <span className="mk-act mk-act-primary">Send as Dana</span>
                    <span className="mk-act">Edit</span>
                    <span className="mk-act">Discard</span>
                  </div>
                </div>
                <div className="mk-panel-foot">
                  Written to <strong>request_events</strong> · sent by{" "}
                  <strong>dana@riverton.gov</strong>
                </div>
              </div>
              <p className="mk-panel-note">
                The response writes itself. It does not send itself.
              </p>
            </div>
            </div>
          </div>
        </section>

        {/* Proof strip */}
        <section className="wrap mk-section">
          <div className="mk-stats mk-reveal">
            {STATS.map((s) => (
              <div key={s.n} className="mk-stat">
                <div className="mk-stat-n">{s.n}</div>
                <div className="mk-stat-l">{s.l}</div>
                <div className="mk-stat-sub">{s.s}</div>
              </div>
            ))}
          </div>
        </section>

        {/* Three pillars */}
        <section className="wrap mk-section" style={{ paddingTop: 0 }}>
          <div className="mk-head">
            <span className="mk-eyebrow" style={{ color: "var(--accent)" }}>
              The shape of the work
            </span>
            <h2 className="mk-h2">Three jobs, and the product does all three.</h2>
            <p className="mk-sub">
              Most records software handles the middle one. The requests you never receive and the
              decisions you have to defend two years later are where the cost actually lives.
            </p>
          </div>
          <div className="mk-pillars">
            {PILLARS.map((p) => (
              <article key={p.t} className="mk-pillar mk-reveal">
                <span className="mk-pillar-n">{p.n}</span>
                <span className="smallcaps" style={{ color: "var(--accent)", marginLeft: 10, fontSize: "0.85rem" }}>
                  {p.t}
                </span>
                <h3>{p.h}</h3>
                <div className="mk-pillar-rule" />
                <p>{p.d}</p>
              </article>
            ))}
          </div>
        </section>

        {/* The operating principle — the load-bearing promise, given its own ground */}
        <section className="mk-band-dark">
          <div className="wrap mk-section">
            <div className="mk-quote mk-reveal">
              <div className="mk-quote-mark" aria-hidden>
                &ldquo;
              </div>
              <p className="mk-quote-t">AI proposes. Staff disposes.</p>
              <p className="mk-quote-b">
                Every AI output in {branding.productName} is a reviewable draft — an Accept / Edit /
                Dismiss card in front of a named human. Nothing legally significant leaves the
                building on model authority. That is why the audit log reads like a defense exhibit
                rather than a liability.
              </p>
              <hr className="letterhead-rule" aria-hidden style={{ marginInline: "auto" }} />
            </div>
          </div>
        </section>

        {/* The roster — the copy-dense heart of the page */}
        <section className="wrap mk-section">
          <div className="mk-head-center">
            <span className="mk-eyebrow" style={{ color: "var(--ai)" }}>
              Under the hood
            </span>
            <h2 className="mk-h2">What the AI is doing, step by step</h2>
            <p className="mk-sub">
              {branding.productName} puts an AI worker at each stage of the request lifecycle. Each
              one drafts; a named member of your staff decides. Here is the whole roster — there is
              no fine print.
            </p>
          </div>
          <div className="mk-roster">
            {AGENTS.map((a, i) => (
              <article key={a.name} className="mk-agent mk-reveal">
                <span className="mk-agent-num" aria-hidden>
                  {String(i + 1).padStart(2, "0")}
                </span>
                <span className="mk-agent-stage">{a.stage}</span>
                <h3>
                  <SparkIcon />
                  {a.name}
                </h3>
                <p>{a.does}</p>
                <p className="mk-agent-human">{a.human}</p>
              </article>
            ))}
          </div>
          <p className="mk-sub" style={{ textAlign: "center", maxWidth: 680, marginInline: "auto", marginTop: 26 }}>
            Every AI action is logged to the same append-only record as human actions — model,
            prompt version, and outcome. And without an AI key configured, {branding.productName}{" "}
            still runs: the workers stand down, the workflow doesn&apos;t.
          </p>
        </section>

        {/* Multi-tenancy + statute */}
        <section className="mk-band-tint">
          <div className="wrap mk-section">
            <div className="mk-head-center">
              <BrandMark size={40} idPrefix="ten" />
              <h2 className="mk-h2" style={{ marginTop: 16 }}>
                One platform. Every agency its own house.
              </h2>
              <p className="mk-sub">
                Each government gets its own portal at its own address — its seal, its statute
                profile, its staff roster, its residents. Tenancy is enforced in the data layer on
                every query, and statute logic is data: California&apos;s 10-day clock,
                Washington&apos;s 5-business-day response, New York&apos;s FOIL — configured, not
                coded.
              </p>
            </div>
            <div className="mk-trio mk-reveal">
              {[
                {
                  h: "Its own address",
                  d: "Every agency lives at its own path with its own seal, accent color and contact block. Residents never see another jurisdiction's branding, and the accent is contrast-checked before it ships.",
                },
                {
                  h: "Its own clock",
                  d: "The statute profile decides business days, observed holidays, and which extension reasons are permitted. Change states and the math changes with it — no code edit, no redeploy.",
                },
                {
                  h: "Its own data",
                  d: "Tenancy is enforced at the data layer on every query, not by a filter someone remembered to add. A conformance suite runs the same assertions against both storage adapters.",
                },
              ].map((c) => (
                <div key={c.h}>
                  <div className="mk-trio-rule" />
                  <h3>{c.h}</h3>
                  <p>{c.d}</p>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* Closing CTA */}
        <section className="mk-band-dark">
          <div className="wrap mk-section">
            <div className="mk-cta">
              <span className="mk-eyebrow">Start where it is cheapest to start</span>
              <h2 className="mk-h2" style={{ marginTop: 14 }}>
                Stand up a records office in an afternoon.
              </h2>
              <p className="mk-sub" style={{ marginInline: "auto", maxWidth: 560 }}>
                Self-signup is open to government email addresses. Bring your state, your
                departments and your seal — the checklist walks you the rest of the way.
              </p>
              <div className="mk-cta-row">
                <Link href="/signup" className="btn btn-gold" style={{ paddingInline: 24, paddingBlock: 12 }}>
                  Create your records office
                </Link>
                <a
                  href={`mailto:hello@brandeis.us?subject=${encodeURIComponent(`${branding.productName} demo`)}`}
                  className="btn btn-outline-light"
                  style={{ paddingInline: 24, paddingBlock: 12 }}
                >
                  Request a walkthrough
                </a>
              </div>
            </div>
          </div>
        </section>
      </main>

      {/* Product footer */}
      <footer className="gov-footer" style={{ marginTop: 0 }}>
        <div className="wrap">
          {/* Dark rev, PINNED — not swapped. The footer's ground is
              --primary-deep, which is dark in BOTH themes, so keying the swap
              off prefers-color-scheme put the light rev's navy wordmark on a
              near-black footer and made it disappear. Swap on the GROUND, not
              the theme. The light rev lives on /signup, whose ground follows
              the visitor. */}
          <img
            src="/brand/brandeis-lockup-dark.png"
            alt={`${branding.productName} — ${branding.tagline}`}
            style={{ width: 300, height: "auto", marginTop: 34, marginBottom: -8 }}
          />
          <div className="mk-foot">
            <div className="mk-foot-col">
              <h4>Product</h4>
              <Link href="/riverton">Live demo</Link>
              <Link href="/signup">Create your records office</Link>
              <Link href="/admin">Platform console</Link>
            </div>
            <div className="mk-foot-col">
              <h4>For residents</h4>
              <Link href="/riverton/archive">Browse released records</Link>
              <Link href="/riverton/track">Track a request</Link>
              <Link href="/riverton/log">Public request log</Link>
            </div>
            <div className="mk-foot-col">
              <h4>Contact</h4>
              <a href="mailto:hello@brandeis.us">hello@brandeis.us</a>
            </div>
          </div>
          <div className="gov-footer-bottom">
            <span>
              © {new Date().getFullYear()} {branding.productName}. {branding.tagline}.
            </span>
            <span>Self-hostable. No accounts required to run it.</span>
          </div>
        </div>
      </footer>
    </div>
  );
}
